server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/josemariapafo/config-properties
          search-paths: config-data
  application:
    name: config-service